configs:
  - name: wfdb_mysql
    type: mysql
    driverClass: com.mysql.mysql-connector-j
    url: jdbc:mysql://${MYSQL_DB_HOST}/${MYSQL_DB_NAME}?useUnicode=true&characterEncoding=utf8
    userName: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASS}
  - name: wfdb_sqlserver
    type: mssql
    driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://waltersitet:1433
    userName: walter
    password: pass
  - name: wfdb_sqlite
    type: sqlite
    driverClass: org.sqlite.JDBC
    url: jdbc:sqlite:d:/walter/data/wfdb.s3db
    userName: walter
    password: pass
  - name: wfdb_oracle
    type: oracle
    driverClass: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@waltersite:1521:wfdb
    userName: walter
    password: pass